# Generated by Django 4.0.3 on 2022-04-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='caregory',
            new_name='category',
        ),
    ]
