# Generated by Django 4.0.3 on 2022-04-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_housekeeper_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeper_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
