# Generated by Django 4.0.3 on 2022-04-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_housekeeper_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housekeeper_leave',
            old_name='message',
            new_name='leave_message',
        ),
    ]
