# Generated by Django 4.0.3 on 2022-04-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_message_housekeeper_leave_leave_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeper_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('housekeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.housekeeper')),
            ],
        ),
    ]
