# Generated by Django 4.0.3 on 2022-04-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_housekeeper_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeeper_feedback',
            name='customer_id',
        ),
    ]
