# Generated by Django 4.0.3 on 2022-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_housekeeper_feedback_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeper_feedback',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
    ]
