# Generated by Django 4.0.3 on 2022-04-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_housekeeper_feedback_feedback_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housekeeper_feedback',
            old_name='feedback',
            new_name='housekeeper_feedback',
        ),
        migrations.RenameField(
            model_name='housekeeper_feedback',
            old_name='feedback_reply',
            new_name='housekeeper_feedback_reply',
        ),
    ]
