# Generated by Django 4.0.3 on 2022-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_housekeeper_feedback_housekeeper_feedback_housekeeper_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper_feedback',
            name='housekeeper_feedback_reply',
            field=models.TextField(),
        ),
    ]
