# Generated by Django 4.0.3 on 2022-04-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_housekeeper_feedback_housekeeper_feedback_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Housekeeper_Feedback',
        ),
    ]
