# Generated by Django 4.0.3 on 2022-04-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_housekeeper_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeper_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housekeeper_feedback_message', models.TextField()),
                ('housekeeper_feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housekeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.housekeeper')),
            ],
        ),
    ]
