# Generated by Django 4.0.3 on 2022-04-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_housekeeper_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Housekeeper_Feedback',
        ),
    ]
