# Generated by Django 4.0.3 on 2022-05-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_housekeeper_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=100)),
                ('booking_contact', models.CharField(max_length=100)),
                ('booking_date', models.CharField(max_length=100)),
                ('booking_days', models.CharField(max_length=100)),
                ('booking_hours', models.TextField()),
                ('booking_address', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service')),
            ],
        ),
    ]
